# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import fieldapp.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labels', fieldapp.fields.ListField()),
            ],
        ),
    ]
