# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import fieldapp.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fieldapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddPdfFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', fieldapp.fields.ContextTypeRestrictedFileField(upload_to='pdf')),
            ],
        ),
    ]
