# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldapp', '0003_poem'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='type',
            field=models.IntegerField(choices=[(1, '\u5510\u8bd7'), (2, '\u5b8b\u8bcd')], default=1),
        ),
    ]
